"""Smoke test for the F1 dashboard generator.

Calls ``generate_dashboard`` against the real repo data and checks the
output HTML is non-trivial (size > 10 KB), contains an inline ``<svg>``
block, and mentions every plan name from the registry.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from generate_f1_dashboard import PLANS, generate_dashboard  # noqa: E402


def test_dashboard_runs(tmp_path: Path) -> None:
    out = tmp_path / "f1.html"
    info = generate_dashboard(out=out)

    # File exists and is non-trivial.
    assert out.exists(), "dashboard HTML was not written"
    size = out.stat().st_size
    assert size > 10 * 1024, f"dashboard HTML too small: {size} bytes (expected > 10 KB)"

    html = out.read_text(encoding="utf-8")

    # Contains inline SVG (the visualization is embedded, not linked).
    assert "<svg" in html, "dashboard is missing inline <svg> block"

    # Every plan name from the registry appears somewhere in the HTML.
    for spec in PLANS:
        assert spec.name in html, f"plan name {spec.name!r} not rendered in dashboard"

    # Core structural markers are present.
    assert "<!DOCTYPE html>" in html
    assert "F1 Dashboard" in html
    assert "Generated by" in html

    # Summary shape from the return value.
    assert info["total"] == len(PLANS)
    assert info["scored"] + info["skipped"] == info["total"]
    assert 0.0 <= info["mean_f1"] <= 1.0
    assert 0 <= info["passing"] <= info["scored"]


def test_dashboard_handles_missing_runs(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """A missing observed_model.json should render a skipped card, not crash."""
    import generate_f1_dashboard as mod

    fake_plans = [
        mod.PlanSpec(
            name="does_not_exist",
            model_rel="runs/__definitely_missing__/observed_model.json",
            gt_rel="tests/fixtures/svg/planta_74m2_openings_gt.yaml",
            subtitle="intentionally missing — fixture for skip path",
        ),
    ]
    out = tmp_path / "missing.html"
    info = mod.generate_dashboard(out=out, plans=fake_plans)

    assert out.exists()
    html = out.read_text(encoding="utf-8")
    assert "not run yet" in html
    assert info["scored"] == 0
    assert info["skipped"] == 1
