"""Extract human-painted soft barriers from a color-coded PNG.

Sister tool of ``tools/extract_human_walls.py`` — same architecture,
same calibration, same L/T-shape decomposition — but the painted
pixels emit to ``consensus.soft_barriers`` instead of
``consensus.walls``. This exists per user mandate 2026-05-12:

    "Human_wall azul só deve representar parede/drywall/alvenaria
    real. Se a célula só não fecha porque falta soft_barrier, criar
    protocolo human_soft_barrier, não pedir pintura azul."

Color contract (planta_74):
- CYAN     #00ffff  →  human soft barrier (peitoril / guarda-corpo /
                        esquadria / parapet line; renders as a low
                        bounded line in SKP, NOT a full-height wall)

The output JSON appends to ``consensus.soft_barriers`` with
``geometry_origin = "human_annotation"``. Polygonize already consumes
soft_barriers as splitting geometry (PR #112), so adding peitoril
linestrokes between adjacent merged rooms is enough to close the
cell — without fabricating masonry that doesn't exist.

Output schema: ``fixtures/planta_74/human_soft_barriers_truth.schema.json``.

Companion: ``tools/apply_human_soft_barriers.py``.
"""
from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import cv2
import numpy as np

THIS = Path(__file__).resolve().parent
sys.path.insert(0, str(THIS))

# Reuse calibration + bbox conversion from the walls tool (same image
# render comes from render_human_walls_annotation_base, so the planta
# rectangle is identical).
from extract_human_walls import (  # type: ignore
    _auto_calibrate,
    _build_color_mask,
    _px_bbox_to_pts,
)

DEFAULT_COLOR_TOLERANCE = 35
MIN_BLOB_AREA_PX = 1500

# Default barrier_type per painted color. CYAN is the canonical
# soft-barrier color (per protocol doc). Operator can override via
# --barrier-type at the CLI for an entire annotation pass, or pick
# different colors here to mean different barrier_types.
DEFAULT_BARRIER_COLORS: dict[str, dict[str, Any]] = {
    "cyan": {"rgb": [0, 255, 255], "barrier_type": "peitoril"},
}


@dataclass
class ExtractedSoftBarrier:
    id: str
    color: str
    barrier_type: str             # peitoril | guarda_corpo | esquadria
    bbox_px: list[float]
    bbox_pts: list[float]
    orientation: str              # 'h' or 'v'
    polyline_pts: list[list[float]]   # 2-pt polyline along long axis
    height_m: float
    geometry_origin: str = "human_annotation"


# Default heights per barrier_type — kept here as a tiny lookup so
# the schema stays in one place. These match the values already used
# elsewhere in the pipeline (PARAPET_HEIGHT_M = 1.10 from
# consume_consensus.rb).
DEFAULT_HEIGHTS_M: dict[str, float] = {
    "peitoril":      1.10,
    "guarda_corpo":  1.10,
    "esquadria":     2.10,
    "parapet":       0.70,
}


def extract(image_path: Path,
            consensus_path: Path,
            color_mapping: dict[str, dict[str, Any]] | None = None,
            tol: int = DEFAULT_COLOR_TOLERANCE,
            min_blob_area: int = MIN_BLOB_AREA_PX,
            barrier_type_override: str | None = None,
            ) -> dict[str, Any]:
    cmap = color_mapping or DEFAULT_BARRIER_COLORS

    img_bgr = cv2.imread(str(image_path), cv2.IMREAD_COLOR)
    if img_bgr is None:
        raise FileNotFoundError(
            f"Could not read image: {image_path}. Paint barriers on "
            f"the base image generated by "
            f"render_human_walls_annotation_base.py and save here."
        )
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    h_px, w_px = img_rgb.shape[:2]

    consensus = json.loads(consensus_path.read_text())
    walls = consensus.get("walls", [])

    calibration = _auto_calibrate(img_rgb, walls)
    if calibration is None:
        raise RuntimeError(
            "Auto-calibration failed — no wall-like pixels found. "
            "Ensure the base image was generated by "
            "render_human_walls_annotation_base.py."
        )
    print(f"[calibrate] image planta px: "
          f"x=[{calibration['img_x0']},{calibration['img_x1']}], "
          f"y=[{calibration['img_y0']},{calibration['img_y1']}]")
    print(f"[calibrate] scale {calibration['scale_x_pt_per_px']:.4f} x "
          f"{calibration['scale_y_pt_per_px']:.4f} pt/px")

    planta_x0 = calibration["img_x0"]
    planta_y0 = calibration["img_y0"]
    planta_x1 = calibration["img_x1"]
    planta_y1 = calibration["img_y1"]
    extracted: list[ExtractedSoftBarrier] = []
    n_rejected_outside_planta = 0
    n_rejected_square = 0
    n_split_l_shapes = 0
    idx = 0
    for color_name, info in cmap.items():
        target = tuple(info["rgb"])
        barrier_type = (barrier_type_override
                          or info.get("barrier_type", "peitoril"))
        height_m = DEFAULT_HEIGHTS_M.get(barrier_type, 1.10)
        mask = _build_color_mask(img_rgb, target, tol)
        if not mask.any():
            continue
        # Same L/T-shape decomposition as walls (corner-joined barriers
        # painted as a single blob need to split into 2 oriented strokes).
        kernel_h = cv2.getStructuringElement(cv2.MORPH_RECT, (40, 5))
        kernel_v = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 40))
        mask_h = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel_h)
        mask_v = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel_v)
        component_masks = [(mask_h, "h_open"), (mask_v, "v_open")]
        decomposed = False
        n_labels_main, _label_img_main, stats_main, _ = (
            cv2.connectedComponentsWithStats(mask, connectivity=8)
        )
        for lbl in range(1, n_labels_main):
            x_px, y_px, w_blob, h_blob, area = stats_main[lbl]
            cx_px = x_px + w_blob / 2
            cy_px = y_px + h_blob / 2
            if not (planta_x0 <= cx_px <= planta_x1
                    and planta_y0 <= cy_px <= planta_y1):
                continue
            if area < 2000:
                continue
            long_side = max(w_blob, h_blob)
            short_side = max(min(w_blob, h_blob), 1)
            if long_side / short_side < 2.5:
                decomposed = True
                break
        scan_masks = component_masks if decomposed else [(mask, "raw")]
        if decomposed:
            print(f"  [decompose] {color_name} blob has L/T shape; "
                  "splitting via directional morphological opening")
        for cur_mask, src_tag in scan_masks:
            n_labels, _label_img, stats, _centroids = (
                cv2.connectedComponentsWithStats(cur_mask, connectivity=8)
            )
            for lbl in range(1, n_labels):
                x_px, y_px, w_blob, h_blob, area = stats[lbl]
                if area < min_blob_area:
                    continue
                cx_px = x_px + w_blob / 2
                cy_px = y_px + h_blob / 2
                if not (planta_x0 <= cx_px <= planta_x1
                        and planta_y0 <= cy_px <= planta_y1):
                    n_rejected_outside_planta += 1
                    continue
                long_side = max(w_blob, h_blob)
                short_side = max(min(w_blob, h_blob), 1)
                if long_side / short_side < 2.0:
                    n_rejected_square += 1
                    continue
                if decomposed:
                    n_split_l_shapes += 1
                bbox_px = (float(x_px), float(y_px),
                            float(x_px + w_blob), float(y_px + h_blob))
                x0_pt, y0_pt, x1_pt, y1_pt = _px_bbox_to_pts(
                    bbox_px, (w_px, h_px), calibration
                )
                w_pt = x1_pt - x0_pt
                h_pt = y1_pt - y0_pt
                if w_pt >= h_pt:
                    orient = "h"
                    cy = (y0_pt + y1_pt) / 2.0
                    polyline = [[round(x0_pt, 3), round(cy, 3)],
                                 [round(x1_pt, 3), round(cy, 3)]]
                else:
                    orient = "v"
                    cx = (x0_pt + x1_pt) / 2.0
                    polyline = [[round(cx, 3), round(y0_pt, 3)],
                                 [round(cx, 3), round(y1_pt, 3)]]
                extracted.append(ExtractedSoftBarrier(
                    id=f"h_sb{idx:03d}",
                    color=color_name,
                    barrier_type=barrier_type,
                    bbox_px=[round(v, 2) for v in bbox_px],
                    bbox_pts=[round(v, 3) for v in (x0_pt, y0_pt,
                                                      x1_pt, y1_pt)],
                    orientation=orient,
                    polyline_pts=polyline,
                    height_m=height_m,
                ))
                idx += 1

    truth = {
        "schema_version": "1.0",
        "source_image": str(image_path).replace("\\", "/"),
        "image_size_px": [int(w_px), int(h_px)],
        "color_mapping": {k: {"rgb": v["rgb"],
                                "barrier_type": v.get("barrier_type",
                                                       "peitoril")}
                            for k, v in cmap.items()},
        "calibration": calibration,
        "consensus_wall_thickness_pts":
            float(consensus.get("wall_thickness_pts", 5.4)),
        "soft_barriers": [asdict(b) for b in extracted],
    }
    print(f"[extract] {len(extracted)} soft_barriers extracted "
          f"from {image_path.name}")
    if n_rejected_outside_planta:
        print(f"  rejected (outside planta region): "
              f"{n_rejected_outside_planta}")
    if n_rejected_square:
        print(f"  rejected (square aspect, not elongated): "
              f"{n_rejected_square}")
    if n_split_l_shapes:
        print(f"  split from L/T-shape via directional opening: "
              f"{n_split_l_shapes}")
    return truth


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--image", type=Path, required=True,
                    help="PNG annotation with CYAN soft-barrier strokes.")
    ap.add_argument("--consensus", type=Path, required=True,
                    help="consensus_human.json (or any with .walls).")
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--barrier-type", type=str, default=None,
                    help="Override barrier_type for all painted strokes "
                         "(peitoril / guarda_corpo / esquadria / parapet).")
    ap.add_argument("--min-blob-area-px", type=int,
                    default=MIN_BLOB_AREA_PX)
    args = ap.parse_args()

    truth = extract(args.image, args.consensus,
                     barrier_type_override=args.barrier_type,
                     min_blob_area=args.min_blob_area_px)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(truth, indent=2))
    print(f"[ok] truth -> {args.out}")


if __name__ == "__main__":
    main()
