"""PNG history manifest — central log of every render generated by the
pipeline, so an external "planta validator" microservice can pick them
up, score them, and report regressions.

Storage layout::

    runs/png_history/
        manifest.jsonl              # append-only, one JSON object per line
        2026-05-02T03-30-00_<id>_axon_3d.png
        2026-05-02T03-30-12_<id>_overlay.png
        ...

Each manifest entry::

    {
      "id": "20260502T033000Z_5286411_axon_3d",
      "created_at": "2026-05-02T03:30:00+00:00",
      "kind": "axon|sidebyside|overlay|skp_view|...",
      "history_path": "runs/png_history/2026-05-02T03-30-00_..._axon_3d.png",
      "original_path": "runs/vector/axon_3d.png",
      "sha256": "<png hash>",
      "source": {
        "skp": {"path": "...", "sha256": "...", "size": 443669, "mtime": "..."} | null,
        "consensus": {"path": "...", "sha256": "...", "schema_version": "1.0.0"} | null,
        "pdf": {"path": "...", "sha256": "..."} | null
      },
      "generator": {"script": "tools/render_axon.py", "git_commit": "<sha>"},
      "params": {...arbitrary kwargs the generator wants logged...},
      "validation": null    # filled in later by the validator microservice
    }

Validator contract: external service reads manifest.jsonl, picks
entries where ``validation == null``, fetches the PNG via
``history_path``, scores it, then PATCHes the entry with::

    {"validation": {"score": 0.91, "issues": [...], "validated_at": "..."}}

Easiest way to PATCH a JSONL file is to rewrite it. The
``apply_validation()`` helper below does exactly that.

Usage::

    from tools.png_history import register
    register("runs/vector/axon_3d.png",
             kind="axon",
             source={"skp": "runs/vector/planta_74.skp",
                     "consensus": "runs/vector/consensus_model.json"},
             generator="tools/render_axon.py",
             params={"camera": "iso", "size": [1280, 720]})
"""
from __future__ import annotations

import datetime as _dt
import hashlib
import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
HISTORY_DIR = REPO_ROOT / "runs" / "png_history"
MANIFEST = HISTORY_DIR / "manifest.jsonl"


def _sha256(path: Path, *, chunk: int = 1 << 20) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            b = f.read(chunk)
            if not b:
                break
            h.update(b)
    return h.hexdigest()


def _git_head() -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", str(REPO_ROOT), "rev-parse", "--short", "HEAD"],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except Exception:
        return "unknown"


def _file_descriptor(path: str | Path | None) -> dict[str, Any] | None:
    if path is None:
        return None
    p = Path(path)
    if not p.exists():
        return {"path": str(p), "missing": True}
    return {
        "path": str(p),
        "sha256": _sha256(p),
        "size": p.stat().st_size,
        "mtime": _dt.datetime.fromtimestamp(p.stat().st_mtime, tz=_dt.timezone.utc).isoformat(),
    }


def register(
    png_path: str | Path,
    *,
    kind: str = "render",
    source: dict[str, str | Path | None] | None = None,
    generator: str | None = None,
    params: dict[str, Any] | None = None,
    copy: bool = True,
) -> dict[str, Any]:
    """Record a generated PNG in the manifest.

    If ``copy=True`` (default), the PNG is copied into ``runs/png_history/``
    with a timestamped name so the original can be overwritten by the next
    pipeline run without losing the history.

    Returns the manifest entry dict.
    """
    p = Path(png_path).resolve()
    if not p.exists():
        raise FileNotFoundError(f"png not found: {p}")

    HISTORY_DIR.mkdir(parents=True, exist_ok=True)

    ts = _dt.datetime.now(tz=_dt.timezone.utc)
    ts_compact = ts.strftime("%Y%m%dT%H%M%SZ")
    ts_filename = ts.strftime("%Y-%m-%dT%H-%M-%S")
    git_sha = _git_head()
    sha = _sha256(p)
    short_id = sha[:8]
    entry_id = f"{ts_compact}_{git_sha}_{p.stem}_{short_id}"

    if copy:
        dest = HISTORY_DIR / f"{ts_filename}_{git_sha}_{p.stem}_{short_id}.png"
        shutil.copy2(p, dest)
        history_path = dest
    else:
        history_path = p

    src = source or {}
    entry: dict[str, Any] = {
        "id": entry_id,
        "created_at": ts.isoformat(),
        "kind": kind,
        "history_path": str(history_path.relative_to(REPO_ROOT)).replace("\\", "/"),
        "original_path": str(p.relative_to(REPO_ROOT)).replace("\\", "/") if p.is_relative_to(REPO_ROOT) else str(p),
        "sha256": sha,
        "size": p.stat().st_size,
        "source": {
            "skp":       _file_descriptor(src.get("skp")),
            "consensus": _file_descriptor(src.get("consensus")),
            "pdf":       _file_descriptor(src.get("pdf")),
        },
        "generator": {
            "script": generator or "unknown",
            "git_commit": git_sha,
        },
        "params": params or {},
        "validation": None,
    }

    with MANIFEST.open("a", encoding="utf-8") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")

    return entry


def list_entries() -> list[dict[str, Any]]:
    if not MANIFEST.exists():
        return []
    with MANIFEST.open(encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


def pending_validation() -> list[dict[str, Any]]:
    return [e for e in list_entries() if e.get("validation") is None]


def apply_validation(entry_id: str, validation: dict[str, Any]) -> bool:
    """Update one entry in-place. Rewrites the JSONL atomically."""
    if not MANIFEST.exists():
        return False
    entries = list_entries()
    matched = False
    for e in entries:
        if e["id"] == entry_id:
            e["validation"] = {
                **validation,
                "validated_at": _dt.datetime.now(tz=_dt.timezone.utc).isoformat(),
            }
            matched = True
            break
    if not matched:
        return False
    tmp = MANIFEST.with_suffix(".jsonl.tmp")
    with tmp.open("w", encoding="utf-8") as f:
        for e in entries:
            f.write(json.dumps(e, ensure_ascii=False) + "\n")
    os.replace(tmp, MANIFEST)
    return True


# ---------------------------------------------------------------------------
# CLI: `python -m tools.png_history register PNG ...` and `list`/`pending`.
# ---------------------------------------------------------------------------
def _cli() -> int:
    import argparse

    ap = argparse.ArgumentParser(description="PNG history manifest CLI")
    sub = ap.add_subparsers(dest="cmd", required=True)

    reg = sub.add_parser("register")
    reg.add_argument("png", type=Path)
    reg.add_argument("--kind", default="render")
    reg.add_argument("--skp", type=Path)
    reg.add_argument("--consensus", type=Path)
    reg.add_argument("--pdf", type=Path)
    reg.add_argument("--generator", default=None)
    reg.add_argument("--param", action="append", default=[],
                     help="key=value, repeatable")
    reg.add_argument("--no-copy", action="store_true")

    sub.add_parser("list")
    sub.add_parser("pending")

    backfill = sub.add_parser("backfill",
                              help="Register every existing *.png under a directory")
    backfill.add_argument("dir", type=Path)
    backfill.add_argument("--kind", default="legacy")
    backfill.add_argument("--skp", type=Path)
    backfill.add_argument("--consensus", type=Path)
    backfill.add_argument("--pdf", type=Path)

    val = sub.add_parser("validate", help="Apply validation to one entry")
    val.add_argument("id")
    val.add_argument("--score", type=float, required=True)
    val.add_argument("--issues", default="[]", help="JSON list of issue strings")
    val.add_argument("--notes", default="")

    args = ap.parse_args()
    if args.cmd == "register":
        params: dict[str, Any] = {}
        for kv in args.param:
            k, _, v = kv.partition("=")
            params[k] = v
        e = register(
            args.png, kind=args.kind,
            source={"skp": args.skp, "consensus": args.consensus, "pdf": args.pdf},
            generator=args.generator, params=params, copy=not args.no_copy,
        )
        print(json.dumps(e, ensure_ascii=False, indent=2))
    elif args.cmd == "list":
        for e in list_entries():
            print(json.dumps(e, ensure_ascii=False))
    elif args.cmd == "pending":
        for e in pending_validation():
            print(json.dumps(e, ensure_ascii=False))
    elif args.cmd == "backfill":
        for png in sorted(args.dir.rglob("*.png")):
            try:
                register(png, kind=args.kind,
                         source={"skp": args.skp, "consensus": args.consensus, "pdf": args.pdf},
                         generator="backfill")
                print(f"[ok] {png}")
            except Exception as ex:
                print(f"[skip] {png}: {ex}")
    elif args.cmd == "validate":
        ok = apply_validation(args.id, {
            "score": args.score,
            "issues": json.loads(args.issues),
            "notes": args.notes,
        })
        print("ok" if ok else "not found")
    return 0


if __name__ == "__main__":
    raise SystemExit(_cli())
